M48
; DRILL file {KiCad (6.0.7)} date Tue Sep 27 15:13:42 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-09-27T15:13:42-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,MixedPlating,1,2
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0315
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0394
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.0433
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T4C0.0598
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T5C0.0630
%
G90
G05
T1
X5.5Y-3.6
X5.8Y-3.6
T2
X5.6Y-3.35
X5.7Y-3.35
X5.8Y-3.25
X5.8Y-3.35
X5.9Y-3.25
X5.9Y-3.35
X6.0Y-3.25
X7.2Y-3.25
X7.2Y-3.35
X7.2Y-3.5
X7.2Y-3.6
T3
X7.0Y-3.25
X7.0Y-3.35
X7.0Y-3.45
T4
X5.3Y-3.95
X5.5Y-3.95
X5.7Y-3.95
X5.9Y-3.95
X6.2Y-3.95
X6.4Y-3.65
X6.4Y-3.95
X6.6Y-3.65
X6.6Y-3.95
X6.8Y-3.65
X6.8Y-3.95
T5
X7.2Y-3.8
X7.2Y-4.0362
X7.385Y-3.9181
T0
M30
