M48
; DRILL file {KiCad (6.0.7)} date Sat Sep 24 10:53:24 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-09-24T10:53:24-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,MixedPlating,1,2
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0315
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0394
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.0433
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T4C0.0598
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T5C0.0630
%
G90
G05
T1
X5.2Y-3.7
X5.4Y-3.4
X5.5Y-3.4
X5.6Y-3.4
X5.6Y-3.7
X5.7Y-3.4
T2
X5.4Y-3.1
X5.5Y-3.1
X5.6Y-3.1
X5.7Y-3.1
X6.1Y-2.3
X6.2Y-2.3
X6.3Y-2.3
X6.65Y-2.05
X6.65Y-3.65
X7.35Y-2.05
X7.35Y-3.65
T3
X7.0Y-3.2
X7.0Y-3.3
X7.0Y-3.4
T4
X5.3Y-3.95
X5.5Y-3.95
X5.7Y-3.95
X5.9Y-3.95
X6.0Y-3.6
X6.2Y-3.6
X6.2Y-3.95
X6.4Y-3.6
X6.4Y-3.95
X6.6Y-3.95
X6.8Y-3.95
T5
X7.2Y-3.8
X7.2Y-4.0362
X7.385Y-3.9181
T0
M30
